### ISSUE TITLE
Provide a `const` function variant of `from_num`

### ISSUE THREAD

**Issue by JoshOrndorff** [encointer/substrate-fixed#3]
Substrate's own fixed point types (eg [Permill](https://substrate.dev/rustdocs/master/sp_arithmetic/struct.Permill.html)) provide `const` functions for creating instances. This is very useful because it allows things like

```rust
const INTEREST_RATE : U32F32 = U32F32::from_num(5) / 100; // 5% interest
```

When the functions are not `const` they cannot be called at compile time and thus constants of these fixed-point types cannot be created.

**Comment by brenzi** [comment]
You could use `from_bits` which is a `const` fn. But I agree this would be nice. I'm happy to take a PR ;-)

**Comment by tspiteri** [comment]
From upstream here, just found this fork and had a look :) This cannot be a const function in this crate because `from_num` depends on the number of fractional bits, so you would have to use some constraints on the `Frac` generic parameter to actually use it as a number. And if you have constraints on the generic parameters, the function cannot be const, at least not in stable Rust. In fact, all const methods behave bitwise-identically whether operating on say `U0F64` or `U32F32`, or even on `FixedU64<()>` which wouldn't make sense.
